### ISSUE TITLE
Score interpretation

### ISSUE THREAD

**Issue by steven0seagal** [ddd9898/DeepNano#2]
Hi, 
First of all thank you for your work it is great. I am using your software and I am wondering how to interpret prediction score from csv file, what value indicates that this antibody will likely interact with other antigen ?

**Comment by ddd9898** [comment]
Hi steven0seagal,
Thanks for your interest. The prediction score ranges from 0 to 1. In general, a higher score indicates a stronger likelihood of interaction between the nanobody and the antigen, but the exact threshold can depend on your preference for precision or recall (our paper used 0.5 as the threshold).

**Comment by steven0seagal** [comment]
Thank you for clarification ;)
